name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  push_gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Set up RubyGems credentials
        run: |
          mkdir -p ~/.gem
          echo "---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials

      - name: Build and push gem
        run: |
          gem build kolom.gemspec
          gem push kolom-*.gem